### ISSUE TITLE
저희 알고리즘 폴더 구조는 어떻게 해야 할까요?

### ISSUE THREAD

**Issue by dipsiiiiiiiiii** [gardnerss/algorithm#2]
예를 들어서
```
level1
ㄴ크레인_인형뽑기_게임
  ㄴ 김관희.js
```

아니면
```
level1
ㄴ김관희_크레인_인형뽑기_게임.js
```

첫 번째 방법은 문제를 폴더별로 구분해서 찾기 훨씬 쉽다는 장점이 있고
두 번째 방법은 폴더를 깊게 만들지 않아서 괜찮아 보입니다!
어떻게 생각하시나요?

**Comment by soongyu** [comment]
제 생각엔 전자가 나아보이네요. 2 번째 방법으로 하게된다면 알고리즘 문제의 갯수가 늘어나게 된다면 찾기가 어려울 것 같아요.
나중에 돌이켜보면서 리뷰를 할 때 문제에 대해 5명이 어떻게 다르게 풀었는지 보려면 1번이 좋지 않을까 싶습니다! @dipsiiiiiiiiii

**Comment by dipsiiiiiiiiii** [comment]
문제 개수가 늘어났을 때를 생각해보면 전자가 훨씬 깔끔할 것 같네요!

**Comment by joonsikyang** [comment]
저도 전자에 한 표👐

**Comment by dipsiiiiiiiiii** [comment]
오케이! 그럼 우선 이렇게 하겠습니다! 다른 분들 다른 의견 있으시면 다시 이슈 열어주세요!👐
